### ISSUE TITLE
Detailed and Searchable FAQ page

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-21-Frontend#10]
We plan to make our FAQs searchable, so that people don't have to go face the trouble of scrolling through the queries.In [faq.js](https://github.com/kossiitkgp/KWoC-21-Frontend/blob/master/src/data/faq.js) file, there is a list of FAQs. Update the FAQs page with a search box and cards

The page may look something like this. While user types the query, the cards containing question and answer showup
![Screenshot from 2021-09-26 17-52-22](https://user-images.githubusercontent.com/44907757/134807929-c1e53c7a-00b3-4600-a9e5-865b122079ea.png)

For search, you may use fuse.js - https://fusejs.io/

**Comment by rakaar** [comment]
The page may look something like this. While user types the query, the cards containing 
![Screenshot from 2021-09-26 17-52-22](https://user-images.githubusercontent.com/44907757/134807929-c1e53c7a-00b3-4600-a9e5-865b122079ea.png)
question and answer showup

**Comment by aniketpathak028** [comment]
Hey @rakaar, I would like to work on this issue could you assign me pls

**Comment by rakaar** [comment]
@aniketpathak028 
Assigned. You can be in touch with @chirag828049 and @sahil-shubham in case of queries and discussion.

**Comment by aniketpathak028** [comment]
Hey @rakaar thanks for the same, I did have a few queries. Will get in touch with @chirag828049 and @sahil-shubham

**Comment by sahil-shubham** [comment]
Fixed.
