### ISSUE TITLE
Student Dashboard changes

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-21-Frontend#11]
In the student Dashboard, let's make changes such that more important things are accessible via Dashboard 

- [x] Link to Stats page rather than whole Stats:- Detailed stats of a student are already provided in the route `/stats/student/USERNAME`, keeping the same thing again on the Dashboard seems unnecessary. Instead we can just show the Commits Count, PRs count, Lines of Code count and provide a link which redirects to the detailed stats page.
- [x] Announcements on the top:- Last time Announcements were buried at the bottom, lets keep such an important thing on the top
- [x] Link for Resources rather than complete resources:- We can have a separate page for Student resources and Mentor resources and Just link the button to it in the Dashboard, as they occupy a lot of place(TO BE DISCUSSED)
- [x] KWoC slack invite link so that the student's doubts can be resolved easily. Discussions on Slack are easy and convenient!

More suggestions and ideas are welcome!
**You are welcome to send Pull Requests for individual Tasks too**! :smiley_cat:

**Comment by SachinMittal1766** [comment]
@rakaar I would like to work on this issue. Pls assign it to me.

**Comment by rakaar** [comment]
hey @SachinMittal1766 
I think some of the tasks present in the issue have been solved. 

@sahil-shubham and @chirag828049 please let @SachinMittal1766 know what tasks are left for this issue and assign them.

I am not updated with the current status of the repo. @sahil-shubham and @chirag828049 can guide you more.

**Comment by chirag828049** [comment]
I have marked the tasks which are already done. 
@SachinMittal1766 you can work on the announcements thing. Also, the individual stats seem to have some problem. You are welcome to fix that too.

**Comment by sahil-shubham** [comment]
@SachinMittal1766 are you still working on this?

**Comment by sahil-shubham** [comment]
This has been dealt it. Closing now.
