### ISSUE TITLE
Statistics Section

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#133]

**Comment by zetabug** [comment]
@harshkhandeparkar I would like to work on this issue. Can you assign this to me.

**Comment by harshkhandeparkar** [comment]
> @harshkhandeparkar I would like to work on this issue. Can you assign this to me.

Sorry but someone else is already working on this. We will open more issues soon, you can work on them!

**Comment by harshkhandeparkar** [comment]
Managed in #219.
