### ISSUE TITLE
Community Section

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#142]
Add a "Join Our Community" section to the landing page with links to our Discord server and Slack.
Links: [Slack](https://join.slack.com/t/kwoc-koss/shared_invite/zt-wlftnk75-VoQHEEB9WpkHfza6~GGpWQ), [Discord](https://discord.gg/efFwh6fnjk).

Please make a PR to the `landing-page` branch.

**Comment by jamnxdev** [comment]
Hello, I want to work on this, please assign it to me, also please provide some more details.

For instance, should I add a "Join our community" section to the footer with Slack and Discord links, or should I add the Slack and Discord links under the "Social Groups" section?

<img width="188" alt="image" src="https://github.com/kossiitkgp/KWoC-Frontend/assets/65119631/a83f30aa-0059-4017-9179-4bddbed662de">

**Comment by harshkhandeparkar** [comment]
> Hello, I want to work on this, please assign it to me, also please provide some more details.
> 
> For instance, should I add a "Join our community" section to the footer with Slack and Discord links, or should I add the Slack and Discord links under the "Social Groups" section?
> <img alt="image" width="188" src="https://user-images.githubusercontent.com/65119631/278696888-a83f30aa-0059-4017-9179-4bddbed662de.png">

We would like to have a separate section as part of the landing page itself, not the footer. Thanks for showing interest!
