### ISSUE TITLE
Add FAQ Questions related to Stats 

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-21-Frontend#16]
- How do we collect stats
- What exactly are PRs and commits count denote
- Why my commits are not showing up
- How to reconfigure username properly on github

Related mistake from Past year - https://github.com/kossiitkgp/mistakes/blob/master/kwoc20.md#4-awareness-about-what-exactly-are-counted-in-stats---need-for-faq-

**Comment by likhith2003** [comment]
https://github.com/kossiitkgp/KWoC-21-Frontend/pull/41/files  .check the stats faq file in this pull. @rakaar

**Comment by likhith2003** [comment]
i guess this issue is resolved @rakaar

**Comment by rakaar** [comment]
If all questions are resolved. Feel free to close it.
