### ISSUE TITLE
Shuffle!

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-21-Frontend#17]
We plan to shuffle the projects and stats. Make a separate file named `shuffle.js`, which includes a function `shuffleArray`, which takes 2 parameters
1. Array - the array that needs to be shuffled
2. n - size of club
Returns the shuffled array

While shuffling we want a set of things to be together. For example, for projects, while shuffling we shuffle clubs, where each club is a collection of 3 projects.  For example in set of projects [p1, p2,p3,p4,p5,p6,p7,p8,p9] when shuffled `p1,p2,p3` stay together, `p4,p5,p6` stay together , `p7,p8,p9` stay together.

You may refer - https://github.com/kossiitkgp/KWoC-21-Frontend/blob/master/src/components/projects/Projects.js#L24

Once the shuffle function is made
1. Remove the shuffling logic in the function `Project.js` and import the new shuffle function from `shuffle.js` and use it. Keep club size as 3. 
2. Import the same shuffle function in this file - https://github.com/kossiitkgp/KWoC-21-Frontend/blob/master/src/components/tables/StudentsTable/StudentsTable.js#L178. And shuffle the **rows of a single page**, keeping club size 1

**Comment by samar-1601** [comment]
I want to work on this issue.

**Comment by sahil-shubham** [comment]
Thanks for your interest in contributing @samar-1601, I have assigned the issue to you. Let me know if you face any issues and we can solve them together.

**Comment by samar-1601** [comment]
> Import the same shuffle function in this file - https://github.com/kossiitkgp/KWoC-21-Frontend/blob/master/src/components/tables/StudentsTable/StudentsTable.js#L178. And shuffle the rows of a single page, keeping club size 1

I am not able to understand where I have to shuffle the rows in the given link.

**Comment by rakaar** [comment]
@samar-1601 
Sorry, it seems the wrong line number was mentioned in the comment. Here is the right one -  https://github.com/kossiitkgp/KWoC-21-Frontend/blob/master/src/components/tables/StudentsTable/StudentsTable.js#L213

We need to basically shuffle the rows before iterating through them. Suppose the function you wrote has name -`shuffle`. Then in code, it should be something like this .
```
shuffle(rows,1).map((row) =>)
```

**Comment by samar-1601** [comment]
Done!
@rakaar I have implemented the changes. Kindly merge it after reviewing. Also, I am participating in Hacktoberfest, so I will be glad if you tag "hactoberfest-accepted" to it.
