### ISSUE TITLE
Add Past Programs Section and Page

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#172]
- [ ] Add a page with links to previous KWoC program archives.
- [ ] Add a section on the landing page for this.

**Comment by zetabug** [comment]
I would like to work on this @harshkhandeparkar

**Comment by harshkhandeparkar** [comment]
> I would like to work on this @harshkhandeparkar

Sure, go ahead! These are the links to the archives:
- https://kwoc19.kossiitkgp.org
- https://kwoc20.kossiitkgp.org
- https://kwoc21.kossiitkgp.org
- https://kwoc22.kossiitkgp.org
