### ISSUE TITLE
"Join Slack" button on the Navbar

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-21-Frontend#18]
Queries can be quickly resolved on Slack. But many participants are not aware that Slack exists. Lets keep the "Join Slack" as an invite link to Slack on the navbar.

Here is the permanent invite link - https://join.slack.com/t/kwoc-koss/shared_invite/zt-wlftnk75-VoQHEEB9WpkHfza6~GGpWQ

**Comment by xypnox** [comment]
Also mailing the link in the introduction to KWoC with a recommendation to join will also work. We can ask them to join with there registered email. This help to map emails to slack users, which can be user to mail all the unregistered members to join slack.

**Comment by wweverma1** [comment]
@rakaar can I start working on this issue?

**Comment by sahil-shubham** [comment]
Hi there @wweverma1, you are free to take this issue. Let us know if you face any issue.

**Comment by wweverma1** [comment]
@rakaar @sahil-shubham 
I've raised a PR against this Issue.
PR: https://github.com/kossiitkgp/KWoC-21-Frontend/pull/20
Kindly merge it after reviewing.
Also can you please tag "hacktoberfest-accepted" label to it?

**Comment by sahil-shubham** [comment]
I will take a look @wweverma1 Thanks
