### ISSUE TITLE
Handle readme link

### ISSUE THREAD

**Issue by proffapt** [kossiitkgp/KWoC-21-Frontend#181]
We have following option:
- Set default value of it to `$github_url` + `#readme`
- Don't bother to ask, take it as default

Would prefer the first one..

![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/86282911/113be095-739a-4407-a02c-f910cfce88eb)

**Comment by snowden-fu** [comment]
what is url of it, i tried so many times, but not found @proffapt

**Comment by snowden-fu** [comment]
plz assign this to me

**Comment by proffapt** [comment]
The url is the url participant enters their GitHub repo.

And btw, the coding period will start from 9th December.

**Comment by snowden-fu** [comment]
> The url is the url participant enters their GitHub repo.
> 
> And btw, the coding period will start from 9th December.

is it a page for a mentor registering their project? if true, how can I login as mentor role

**Comment by harshkhandeparkar** [comment]
> > The url is the url participant enters their GitHub repo.
> > And btw, the coding period will start from 9th December.
> 
> is it a page for a mentor registering their project? if true, how can I login as mentor role

In development, you can remove the code that redirects you from that page. Alternatively, you could also set up the [backend](https://github.com/kossiitkgp/KWoC-Backend) locally, but that would be unnecessary for this PR.

**Comment by Nafisay** [comment]
@fuzheng1998 any updates? If not, we will have to reassign this issue to someone else.

**Comment by snowden-fu** [comment]
> @fuzheng1998 any updates? If not, we will have to reassign this issue to someone else.

I am working on locally, since above mention coding start at 9, so I didn't move forward very fast

**Comment by Nafisay** [comment]
> > @fuzheng1998 any updates? If not, we will have to reassign this issue to someone else.
> 
> I am working on locally, since above mention coding start at 9, so I didn't move forward very fast

Ok, no problem!

**Comment by Nafisay** [comment]
Any updates @snowden-fu ?

**Comment by harshkhandeparkar** [comment]
We are planning on removing the readme link altogether since we are doing nothing with it.
