### ISSUE TITLE
Randomize Projects List

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#185]
The projects list on the projects can be randomized each time for better discovery.

**Comment by asmitdeb** [comment]
Hi, I would like to work on this, can you help me get started? Also, is this good for beginners?

**Comment by harshkhandeparkar** [comment]
> Hi, I would like to work on this, can you help me get started? Also, is this good for beginners?

Welcome! You can start by looking at [this](https://github.com/kossiitkgp/KWoC-Frontend/blob/6e81c3140d60f3f0761c1dde84e712ec158b31d8/src/pages/Projects.tsx#L35) line of code. Here, `response.response` is an array of projects. The order of this list has to be randomized (shuffled). You can use any library for this or write your own code.

**Comment by VineeTagarwaL-code** [comment]
i would love to work on this issue , please assign @harshkhandeparkar

**Comment by harshkhandeparkar** [comment]
> i would love to work on this issue , please assign @harshkhandeparkar

@asmitdeb has already requested to work on this. If they don't want to continue, I'll assign this to you.

**Comment by asmitdeb** [comment]
I cloned the backend and frontend repos, but I am unable to link them together.
I am getting this error when building the backend
![Xnip2023-11-27_19-04-50](https://github.com/kossiitkgp/KWoC-Frontend/assets/47671715/09b574c5-91ae-4d3e-8959-118bf9ae4f03)

Also, in [this](https://github.com/kossiitkgp/KWoC-Frontend/blob/6e81c3140d60f3f0761c1dde84e712ec158b31d8/src/pages/Projects.tsx#L35) line, `response.response` returns a JSON Object right?

**Comment by harshkhandeparkar** [comment]
> I cloned the backend and frontend repos, but I am unable to link them together. I am getting this error when building the backend ![Xnip2023-11-27_19-04-50](https://private-user-images.githubusercontent.com/47671715/285884227-09b574c5-91ae-4d3e-8959-118bf9ae4f03.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDIzNTIsIm5iZiI6MTcwMTEwMjA1MiwicGF0aCI6Ii80NzY3MTcxNS8yODU4ODQyMjctMDliNTc0YzUtOTFhZS00ZDNlLTg5NTktMTE4YmY5YWU0ZjAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYjg2NjQ2NGQyNDg1Nzg0MTE0MWI0Y2NlNTE3NmY1ZDQ5MjJlOGY3MjQ1NDVlMjJiOGQ2Mjg4NDFkNzdhMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cE6TWL-sfU6Y8p07o_hxpoYiQz2ST5dlGqYVS4sxd4U)

Create a `.env` file in the frontend repo and copy the contents of the `.env.template` file to it.

> Also, in [this](https://github.com/kossiitkgp/KWoC-Frontend/blob/6e81c3140d60f3f0761c1dde84e712ec158b31d8/src/pages/Projects.tsx#L35) line, `response.response` returns a JSON Object right?

No it should be a Javascript object.

**Comment by asmitdeb** [comment]
This should work right?
<img width="1166" alt="image" src="https://github.com/kossiitkgp/KWoC-Frontend/assets/47671715/a267d18d-c35b-48b6-a5f9-f05cdfe926e0">
Will it count for Kwoc if I make a PR now?

**Comment by VineeTagarwaL-code** [comment]
no @asmitdeb this wont but who cares make the PR for good

**Comment by VineeTagarwaL-code** [comment]
yeah this should work , how about adding a async and await here to make sure that it shuffles first and then the project state gets populated ?

**Comment by asmitdeb** [comment]
I am not exactly familiar with promises, is this fine?
<img width="639" alt="image" src="https://github.com/kossiitkgp/KWoC-Frontend/assets/47671715/217cc6b8-9fbe-4b33-82cf-5b6804d00ef9">

Please review the changes @harshkhandeparkar

**Comment by harshkhandeparkar** [comment]
@asmitdeb could you open a pull request? It would be easier to review it. It is fine if your PR is not complete.

**Comment by asmitdeb** [comment]
Done @harshkhandeparkar
