### ISSUE TITLE
How to login as mentor or student by GitHub 

### ISSUE THREAD

**Issue by snowden-fu** [kossiitkgp/KWoC-21-Frontend#186]
I understand OAuth by Github can be configured in env file, but I have registered as student, how can I login as mentor?

**Comment by koss-service** [comment]
You can only apply as a student or a mentor. As mentioned in [FAQs](https://kwoc.kossiitkgp.org/faq).

**Comment by snowden-fu** [comment]
> You can only apply as a student or a mentor. As mentioned in [FAQs](https://kwoc.kossiitkgp.org/faq).

I think you misunderstood my question. What I mean is that while development, for a page I have to login for access. As you said, I only can be a student or mentor, so how can I go to the mentor's page for development?

**Comment by harshkhandeparkar** [comment]
> > You can only apply as a student or a mentor. As mentioned in [FAQs](https://kwoc.kossiitkgp.org/faq).
> 
> I think you misunderstood my question. What I mean is that while development, for a page I have to login for access. As you said, I only can be a student or mentor, so how can I go to the mentor's page for development?

@fuzheng1998 during development, you can remove the code preventing you from opening the page manually. If you need any further guidance on this, ask on #kwoc-frontend on Discord.
