### ISSUE TITLE
Feature request to add hovering cards in the "WHY KWOC?" section.

### ISSUE THREAD

**Issue by jaibhedia** [kossiitkgp/KWoC-21-Frontend#189]
I've added a hovering card in the "WHY KWOC?" section, which gets expanded by 1:1 and rotates as well, giving it a responsive and fun feel.
Preview:
![trial](https://github.com/kossiitkgp/KWoC-Frontend/assets/57904885/e94b5e1e-d3fd-407a-a153-887ca6b429dd)

**Comment by harshkhandeparkar** [comment]
@jaibhedia Thanks for your suggestion! But please wait for a maintainer's approval before opening a pull request. The maintainers may suggest changes or decline the feature request if it doesn't align with the project goals, and you may do a lot of redundant work.

In this case, the animation is unnecessary and makes reading and copying the text harder. I am closing this issue and PR for now.

Please do not get demotivated by this. You are always free to work on any open issues that have yet to be assigned to anyone. Any other suggestions from you are also always welcome!

**Comment by jaibhedia** [comment]
sorry, for the PR without the approval, I'll take care next time and we'll definitely come up with new features.
