### ISSUE TITLE
Text selection cursor at "KWOC 2023"

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [kossiitkgp/KWoC-21-Frontend#191]
# Description
 The cursor when hovering over the main page's "KWOC 2023" , we are getting the text selection cursor which doesnt suits the UI 
 
 # ✅Solution :
Instead of it we can put pointer cursor when hovering over it to make it look more better 

# Screenshots
![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/91052168/95aeccfc-740e-4a07-b5b2-12390aa1b6f9)

**Comment by VineeTagarwaL-code** [comment]
I would like to work on this , please assign me

**Comment by harshkhandeparkar** [comment]
A better solution imo would be to disable selection. What do you think?

**Comment by VineeTagarwaL-code** [comment]
yeah sure did it as well as i added a cursor

**Comment by VineeTagarwaL-code** [comment]
and just as we are adding a cursor on it , i added reload feature to it ... if clicked the website would get reloaded
