### ISSUE TITLE
Update Contributing Guidelines

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#199]
Include the following in the CONTRIBUTING.md guidelines:
- [ ] A requirement to comment on the issue and wait for being assigned.

**Comment by asmitdeb** [comment]
I would like to work on this, please assign this issue to me

**Comment by harshkhandeparkar** [comment]
@asmitdeb please don't open a PR before being assigned an issue. Multiple people may end up working on the same issue :)

**Comment by asmitdeb** [comment]
Sorry, I'll keep that in mind
