### ISSUE TITLE
Don't use URLs directly

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-21-Frontend#2]
Constants like BACKEND_URL, BACKEND_STATS_API, MID_EVAL_DATE and so on should be kept in `src/constants/constants.js`. But at some places it is used directly for example in MentorDashboard.js, MentorStats.js, the URLs are used directly without importing from constants.js

At such places, remove the hardcoding of the URL and import the URL from `constants.js` and use it to fetch the requests

**Comment by samar-1601** [comment]
I would like to work on this issue.

**Comment by sahil-shubham** [comment]
Cool, go ahead @samar-1601

**Comment by samar-1601** [comment]
@rakaar I have implemented the changes. Kindly merge it after reviewing. Also I am participating in hactoberfest so I will be gald if you tag "hactoberfest-accepted" to it.
