### ISSUE TITLE
Right Align Profile Picture

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#200]
The profile picture on mobile navbar is left aligned. It should be right aligned like the other links.

![Screenshot_20231128_142150_Firefox](https://github.com/kossiitkgp/KWoC-Frontend/assets/34770591/c937010f-7dda-4b63-a7b8-f9481355e240)

**Comment by sarthakroy107** [comment]
I would like work on this issue, can you please assign me

**Comment by harshkhandeparkar** [comment]
> I would like work on this issue, can you please assign me

Sure, go ahead!
