### ISSUE TITLE
Warn That Mentors Cannot Register As Student

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#201]
Show a warning on the mentor and student forms that a mentor cannot register as a student and vice versa.

**Comment by GautamRaj-12** [comment]
Hey, I would like to contribute to this issue. Can you assign me?

**Comment by harshkhandeparkar** [comment]
> Hey, I would like to contribute to this issue. Can you assign me?

Sure, go ahead!

**Comment by GautamRaj-12** [comment]
I set the project up locally but as the issue says that "I need to show warning on mentor and student form" but when I click on mentor login or student login. It takes me to github and says 404 error. There is no registration form. So where do I show the warning.

Home page works fine on local setup
![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/64408989/e5ed66e1-c562-4987-ae9b-2213b6ffcd7c)

But, when I click on student login or mentor login, It shows me the following:
![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/64408989/70df7ce9-fb68-4cbc-a5cd-5a133c9a4d72)

**Comment by harshkhandeparkar** [comment]
> I set the project up locally but as the issue says that "I need to show warning on mentor and student form" but when I click on mentor login or student login. It takes me to github and says 404 error. There is no registration form. So where do I show the warning.
> 
> Home page works fine on local setup ![image](https://private-user-images.githubusercontent.com/64408989/286328218-e5ed66e1-c562-4987-ae9b-2213b6ffcd7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjQ2MDcsIm5iZiI6MTcwMTI2NDMwNywicGF0aCI6Ii82NDQwODk4OS8yODYzMjgyMTgtZTVlZDY2ZTEtYzU2Mi00OTg3LWFlOWItMjIxM2I2ZmZjZDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEzMjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MjU3ZDY0ZGYyY2FkOGI0NDc5NjliMmM4NzQxMzA3MWY3ZTkwNWFkYWNlMTcwZDFkYmI4ZjAzYTRmZWRiOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvZ07zDaaCJ1p2FDCTcv8q7JwqmwWvW4lXVnKs94tI4)
> 
> But, when I click on student login or mentor login, It shows me the following: ![image](https://private-user-images.githubusercontent.com/64408989/286328580-70df7ce9-fb68-4cbc-a5cd-5a133c9a4d72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjQ2MDcsIm5iZiI6MTcwMTI2NDMwNywicGF0aCI6Ii82NDQwODk4OS8yODYzMjg1ODAtNzBkZjdjZTktZmI2OC00Y2JjLWE1Y2QtNWExMzNjOWE0ZDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEzMjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmY2Y5NmUxZjRmNmVmYzY1YjAxOTg5NDJiNzQ2NTE0NjNhNDI0MGRkNGYxMDMyNTA2ZDU4MjQ3NWI4MjZiZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xHsQTtBrrvSZHRdKVaKSPNEO9QWM3g8fI8PPqdnxMOQ)

For testing, you can comment [these](https://github.com/kossiitkgp/KWoC-Frontend/blob/6694b929f18c68e8ae3fdcd61561f5cdcfcfed73/src/pages/RegistrationForm.tsx#L22-L28) lines and open `/form/mentor` locally.
