### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#205]
Add the following issue templates in `.github/ISSUE_TEMPLATE/`:
- Feature Request
- Bug Report
- Good First Issue/First Timers Only: Includes links to all the necessary information/instructions a first timer might require.

All issues must have contribution guidelines mentioned: 
- If you want to work on an issue, please let us know in a comment below.
- Do not begin work on the issue unless it has been assigned to you.
- If you do not respond in 3 days, the issue may be reassigned to someone else.

**Comment by sarthakroy107** [comment]
Can you please assign me to this issue

**Comment by harshkhandeparkar** [comment]
> Can you please assign me to this issue

Go ahead :)
