### ISSUE TITLE
Changing the cursor icon

### ISSUE THREAD

**Issue by dontwike** [kossiitkgp/KWoC-21-Frontend#208]
### Describe the feature/bug

The cursor pointer of the website is not matching with the theme so I'll put a pointer which does.

### Steps to reproduce bug/implement feature

Only have add a line in main CSS file about cursor pointer design 

### Resources

data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='26' height='31' fill='none' viewBox='0 0 26 31'%3E%3Cpath fill='%23fff' fill-rule='evenodd' stroke='%23010101' stroke-linecap='square' stroke-width='2.5' d='M21.993 14.425 2.549 2.935l4.444 23.108 4.653-10.002 10.347-1.616Z' clip-rule='evenodd'/%3E%3C/svg%3E

**Comment by Nafisay** [comment]
@julesglad please refrain from making a pr before the issue has been assigned to you. Kindly adhere to the rules given here [https://github.com/kossiitkgp/KWoC-Frontend/blob/truth-redefined-again/CONTRIBUTING.md#guidelines](url)

**Comment by dontwike** [comment]
Is this issue closed? Because i created a issue on it

**Comment by Nafisay** [comment]
@dontwike people might use different types of cursors due to accessibility reasons. Hence, we are closing this issue as unplanned.

**Comment by dontwike** [comment]
Ok
