### ISSUE TITLE
Display Mentor Dashboard Statistics

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-21-Frontend#211]
### Describe the feature

The following statistics need to be shown on the mentor dashboard:
- [x] #213
- [x] A list of pull requests for each of the projects
- [x] A list of all students who have contributed to their projects
- [x] Project-wise statistics

**Comment by pranjal3060** [comment]
I am interested

**Comment by Nafisay** [comment]
This is a planning issue. The above mentioned issue will be taken up individually. If you're interested in the 1st issue, kindly comment on #213
