### ISSUE TITLE
Display Student Dashboard Statistics

### ISSUE THREAD

**Issue by Nafisay** [kossiitkgp/KWoC-21-Frontend#212]
Display student's overall stats in the `Student Dashboard`

- `Total PRs`
- `Total commits`
- `Languages used`

Here are some references:

- https://github.com/kossiitkgp/KWoC-Backend
- https://github.com/kossiitkgp/KWoC-Backend/blob/main/models/students.go
- https://github.com/kossiitkgp/KWoC-Backend/tree/main/utils

Note: Please **comment** if you want to take up this issue and wait for it to be assigned to you. Do not start working on this issue if you have not been assigned to it.

**Comment by Nupoor10** [comment]
Hello, Can I work on this issue?

**Comment by Nafisay** [comment]
Yes you can

**Comment by Nafisay** [comment]
You can start working now

**Comment by Nafisay** [comment]
Any updates @Nupoor10 ?

**Comment by Nupoor10** [comment]
Hello, I am working on this, will update before EOD

**Comment by Nupoor10** [comment]
Hello, I tried working on this issue however there are quite a few things I don't know yet regarding the technologies used. My apologies, I am unassigning myself.

**Comment by harshkhandeparkar** [comment]
> Hello, I tried working on this issue however there are quite a few things I don't know yet regarding the technologies used. My apologies, I am unassigning myself.

@Nupoor10 you are always free to ask us doubts. We will guide you in the right direction. If you are still up for it, we could tell you where to start.

**Comment by harshkhandeparkar** [comment]
This issue is no longer free to work on.
