### ISSUE TITLE
Display Mentor Dashboard Statistics

### ISSUE THREAD

**Issue by Nafisay** [kossiitkgp/KWoC-21-Frontend#213]
Display mentor's overall stats in the `Mentor Dashboard`

- `Total PRs`
- `Total commits`
- `Languages used`

Here are some references:

- [https://github.com/kossiitkgp/KWoC-Backend](url)
- [https://github.com/kossiitkgp/KWoC-Backend/blob/main/models/mentors.go](url)
- [https://github.com/kossiitkgp/KWoC-Backend/tree/main/utils](url)

Note: Please **comment** if you want to take up this issue and wait for it to be assigned to you. Do not start working on this issue if you have not been assigned to it.

**Comment by pranjal3060** [comment]
Please assign this to me

**Comment by Nafisay** [comment]
You can start working on it now @pranjal3060

**Comment by Nafisay** [comment]
Any updates @pranjal3060 ?

**Comment by pranjal3060** [comment]
![iko](https://github.com/kossiitkgp/KWoC-Frontend/assets/119282619/a8208661-0401-4370-bc27-736cda78f722)

**Comment by pranjal3060** [comment]
![ikol](https://github.com/kossiitkgp/KWoC-Frontend/assets/119282619/87cc2aab-71b8-44f2-b989-d508d3182d9d)

**Comment by pranjal3060** [comment]
> Any updates @pranjal3060 ?

![iko](https://github.com/kossiitkgp/KWoC-Frontend/assets/119282619/e6cf33d0-d330-4391-ac38-0e312f5c0c91)
