### ISSUE TITLE
Mouse Transition Effect

### ISSUE THREAD

**Issue by MitulSonagara** [kossiitkgp/KWoC-21-Frontend#214]
### Describe the feature

I want to add a mouse transition effect on the main KWOC frontend. It will look like as the snow particles are falling on the main page, same small snow particles will be glow where ever mouse pointer will glow. Please assign me this issue so that i can start working on this.

### Additional context

I am contributing under KWOC 2023

### Additional Information

- [X] I have used the search function to check if an issue already exists
- [X] I'd like to work on this issue

**Comment by Nafisay** [comment]
> same small snow particles will be glow where ever mouse pointer will glow

Can you please elaborate on this

**Comment by MitulSonagara** [comment]
It will look like this 

https://github.com/kossiitkgp/KWoC-Frontend/assets/95460188/dfdba53a-a30b-4742-80cb-54eb504087e2

**Comment by Nafisay** [comment]
Okay, go ahead!
