### ISSUE TITLE
Improve search box

### ISSUE THREAD

**Issue by jamnxdev** [kossiitkgp/KWoC-21-Frontend#215]
### Describe the feature

I would like to add a clear input button in faq search and also the clear option should appear when the input length > 0.

### Additional context

The clear button should appear only if the input length is > 0
![IMG_20231209_135820](https://github.com/kossiitkgp/KWoC-Frontend/assets/65119631/d7610802-4a66-445f-bb45-face79f54ad0)

A clear input button here
![IMG_20231209_135830](https://github.com/kossiitkgp/KWoC-Frontend/assets/65119631/dc05035f-cc4c-48bf-a611-969e19aa7e93)

Please assign me this.

### Additional Information

- [X] I have used the search function to check if an issue already exists
- [x] I'd like to work on this issue

**Comment by snowden-fu** [comment]
@Jaimin25 please assign this to me, i have completed locally.

**Comment by jamnxdev** [comment]
> @Jaimin25 please assign this to me, i have completed locally.

Also don't start working on any issue before it's assigned, it's written in contribution.md

![IMG_20231210_091453.jpg](https://github.com/kossiitkgp/KWoC-Frontend/assets/65119631/f10ab6f1-b83c-4b3f-97ea-1ee38b2671d1)

**Comment by snowden-fu** [comment]
> > @Jaimin25 please assign this to me, i have completed locally.
> 
> Also don't start working on any issue before it's assigned, it's written in contribution.md
> 
> ![IMG_20231210_091453.jpg](https://github.com/kossiitkgp/KWoC-Frontend/assets/65119631/f10ab6f1-b83c-4b3f-97ea-1ee38b2671d1)

PR Cancelled.

**Comment by snowden-fu** [comment]
so @Jaimin25 would you like to assign it to me this time?

**Comment by jamnxdev** [comment]
> so @Jaimin25 would you like to assign it to me this time?
> 

I mentioned that I want to work on this issue and I m not the one who can assign issues 😅

**Comment by Nafisay** [comment]
@Jaimin25 you can now working on this issue
