### ISSUE TITLE
Design the landing page cards with animations

### ISSUE THREAD

**Issue by Souvik34** [kossiitkgp/KWoC-21-Frontend#221]
Will use css hover effects and certain js animations to make the event cards more dynamic and vibrant

**Comment by Nafisay** [comment]
@Souvik34 what exactly do you have in mind, can you please elaborate?

**Comment by Souvik34** [comment]
Actually I want to add 3D hover effects on these cards.
<img width="867" alt="Screenshot 2023-12-15 184442" src="https://github.com/kossiitkgp/KWoC-Frontend/assets/98397984/637e69ba-9960-4be6-ba47-44242594e6db">
 I would also like to add certain animations for these cards to make them more attractive.
Further I would also be happy to contribute to the buttons of the landing page. 

If you assign me,  I shall be happy to contribute to this

**Comment by harshkhandeparkar** [comment]
@Souvik34 We would try to avoid 3D animations as it would reduce readability and make copying text (for reference) more difficult. Also on some devices, the animations could be too resource-intensive.

**Comment by Souvik34** [comment]
Actually what I meant by 3D is it will have a slight tilt effect on hover and will add some glow animations. It won't make the website slow because I will do it entirely in css

**Comment by Nafisay** [comment]
After a lot of discussion, we have come to the conclusion of closing this issue as it is not urgent. Sorry for any inconveniences caused. Please try opening new issues or contribute to existing ones. Thank you.
