### ISSUE TITLE
Modify the FAQ's page with accordians

### ISSUE THREAD

**Issue by mendacium-a11y** [kossiitkgp/KWoC-21-Frontend#222]
### Describe the feature

Instead of the current nested bullet points for FAQ's on the website, we can use accordions to display it

### Why do you think this feature should be implemented?

Accordions would help skim through all the FAQ's quickly and help a little bit of readability as the dark background can put a slight strain 

### Additional Information

- [X] I have used the search function to check if an issue already exists
- [X] I'd like to work on this issue

**Comment by Nafisay** [comment]
You can start working on it @mendacium-a11y

**Comment by mendacium-a11y** [comment]
Will get to it, thanks
