### ISSUE TITLE
Custom scroll bar

### ISSUE THREAD

**Issue by Souvik34** [kossiitkgp/KWoC-21-Frontend#229]
### Describe the feature

Having a custom scroll bar

### Additional Information

- [X] I have used the search function to check if an issue already exists
- [X] I'd like to work on this issue

**Comment by Nafisay** [comment]
Go ahead @Souvik34 !

**Comment by Nafisay** [comment]
Any updates @Souvik34 ?

**Comment by Souvik34** [comment]
Added one!
