### ISSUE TITLE
<Frequently Asked Questions div overlapping the navbar in faq pages>

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [kossiitkgp/KWoC-21-Frontend#232]
### Describe the bug

![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/91052168/081d2dbe-a5b3-499b-8d02-75de138a43df)

### Steps to reproduce

1. Go to page FAQ
2. Scoll down and see the bug occuring

### Expected behavior

![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/91052168/c549a263-f7a7-45ec-889e-2a448cb9b349)

### Put here any screenshots or videos (optional)

i have already fixed this , please assign me so i can raise a pr for the raised issue

### Additional Information

- [X] I have used the search function to check if an issue already exists
- [X] I'd like to work on this issue

**Comment by VineeTagarwaL-code** [comment]
i have already fixed the issue , please assign so i can raise a pr that fixes this issue

**Comment by Nafisay** [comment]
Thank you for noticing the bug! You can raise a pr now

**Comment by VineeTagarwaL-code** [comment]
@Nafisay yeah please review and merge it
