### ISSUE TITLE
<User Section is not resposnive on mobile devices>

### ISSUE THREAD

**Issue by Ayusht777** [kossiitkgp/KWoC-21-Frontend#233]
### Describe the bug

The Div are not aligned on user login / stats page  on mobile devices

### Steps to reproduce

1.Click on user icon open it on mobile devices you will see div like project are misaligned 

### Expected behavior

should be in center on small screen

### Put here any screenshots or videos (optional)

![image](https://github.com/kossiitkgp/KWoC-Frontend/assets/106388215/57806744-00d4-437d-8148-42f2b1e4a441)

### Additional Information

- [X] I have used the search function to check if an issue already exists
- [X] I'd like to work on this issue

**Comment by Ayusht777** [comment]
how do login page will work on local development because when ever i click on login it redirect to github page 404

**Comment by harshkhandeparkar** [comment]
Was the issue fixed? @Ayusht777
