### ISSUE TITLE
Some Links not Visible in Navbar

### ISSUE THREAD

**Issue by rajivharlalka** [kossiitkgp/KWoC-21-Frontend#68]
Screens in width ~800 , the navabar isnt responsive
![image](https://user-images.githubusercontent.com/68731551/144704478-6f06a3d2-4200-4be9-b99d-13523fe7d70c.png)

**Comment by RahulSharma4329** [comment]
i want to work on this issue can you assign this to me

**Comment by iamatifmoin** [comment]
@rajivharlalka 
I want to work on this issue.
Please assign me this.

**Comment by rajivharlalka** [comment]
Sure

**Comment by iamatifmoin** [comment]
@rajivharlalka 
Please review the PR.
