### ISSUE TITLE
Allow an option to Edit detail Project form details

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-21-Frontend#7]
There should be an option to edit the following fields during the middle of KWoC
- Name
- Description
- Tags
- Branch
- Re Fetch README: It is possible that the mentor might have updated the README after submitting the project for KWoC. A button like Re-fetch README should fetch README again from the specified branch and replace the existing README

There should be an edit details button for each project, on clicking the button, a form showing prefilled details should be shown allowing the user to edit the details and click on the Update button.

**Comment by wweverma1** [comment]
@rakaar can I work on this issue?

**Comment by rakaar** [comment]
Hi @wweverma1 
Feel free to work on it. Since this is a slightly big issue, you can start with a WIP Pull Request(just one commit would suffice) and we discuss as we go.

**Comment by wweverma1** [comment]
@rakaar okay I've started working on it.

**Comment by sahil-shubham** [comment]
Mentor dashboard, because they are the ones that fill out a form to register their project for KWoC.

**Comment by wweverma1** [comment]
@rakaar @sahil-shubham Also, we would be requiring a "PUT" route to update the form details in the database.
Is this endpoint developed yet or shall I work on that too?

**Comment by sahil-shubham** [comment]
Just a post request, similar to how it happens for when the first time the form gets submitted. The newer data would overwrite the old one.

**Comment by rakaar** [comment]
Here is the overview

Before the component of the Edit form loads, we make a GET request to the backend, fetch the details of the project. The fetched details are prefilled in the form fields. The form fields can be edited. Once the fields are filled and the user clicks submit, the data is sent to the backend via a POST request.(A PUT request is more appropriate, but that is fine)

Since we don't have the backend deployed anywhere and the endpoints are NOT ready. This is what you can do,  take a dummy state variable  -`projectData`. Before component loads, hardcode it with some data like
```
{
"id": 1,
"name": "KWoC Frontend",
"desc": "Frontend of KWoC written in react",
"tags" : '["react","frontend"]', // Note that this is a stringified array
"branch": "master" 
}
```

The above data should be pre-filled in the form, once the user clicks on submit. For now, you can just print in the console the whole updated state of the project using `console.log`.

For fetching README of the project you can refer the code here - https://github.com/kossiitkgp/KWoC-21-Frontend/blob/master/src/components/ProjectForm.js#L283-L291

cc: @wweverma1 @sahil-shubham

**Comment by rakaar** [comment]
React hook forms
@sahil-shubham

**Comment by rakaar** [comment]
#48 fixes it
