### ISSUE TITLE
Sort feature on students stats not working 

### ISSUE THREAD

**Issue by sidkhuntia** [kossiitkgp/KWoC-21-Frontend#75]
![Screen Shot 2021-12-11 at 17 22 44](https://user-images.githubusercontent.com/77291662/145675493-612a3901-540a-4ef6-962e-9811f455dc53.png)

**Comment by sidkhuntia** [comment]
Can i work on it ? @sahil-shubham  @chirag828049

**Comment by chirag828049** [comment]
Sure go ahead.

**Comment by sahil-shubham** [comment]
@sidkhuntia This was done intentionally, we don't want open source contributions to be competitive as the number of commits is not always proportional to how much work someone has put in. 

What we can do is remove the line "you can sort the rows by clicking on the headers" and write a single line explanation of why we choose to sort the stats table. You are free to make a PR with this change. 

Closing this issue.

**Comment by sidkhuntia** [comment]
Okay. 

@sahil-shubham  will something like this work?
**Stats are shuffled to avoid competition as open source is about contributing.**

**Comment by sahil-shubham** [comment]
@sidkhuntia Sounds good, make a pull request and I will merge it. We can remove the sorting functionality as well as all it does is shuffle again.

**Comment by sidkhuntia** [comment]
@sahil-shubham  i have created a PR, please check. sorry for the trouble

**Comment by sahil-shubham** [comment]
> sorry for the trouble
There was no trouble at all, your concern for creating the issue was understandable.
