### ISSUE TITLE
Cannot run project setup

### ISSUE THREAD

**Issue by SachinMittal1766** [kossiitkgp/KWoC-21-Frontend#80]
I have windows 10 and I am using npm to setup project in my laptop but I am getting error after npm start.
Can anyone tell steps after cloning the repo to run? I have followed - npm install and then npm start.

**Comment by chirag828049** [comment]
We are using yarn for package management. 

The right commands are :
1. `yarn` to install the required packages
2. `yarn start` to start the localhost

Closing the issue. If you face further difficulties, you can reach us via discord.
