### ISSUE TITLE
Can't add more than one project

### ISSUE THREAD

**Issue by proffapt** [kossiitkgp/KWoC-21-Frontend#97]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/86282911/204072742-e71c9455-823e-41e4-bce2-5bcb003bd93d.png">

**Comment by proffapt** [comment]
@Yureien isse bhi dekhlo, mujhe ata toh kar deta :)
but ye toh hona chahiye mere friends bhi bol rahe do teen projects daalne ke soche the wo

**Comment by rajivharlalka** [comment]
@proffapt will address this too, but ig it's not very important at the moment. Need to see how things are handled as I remember I adding kwoc frotnend and backend both last year

**Comment by sahil-shubham** [comment]
Should be fixed once #106 gets merged.

**Comment by proffapt** [comment]
I am using the test build right now to add more projects; It works fine.. just need to be shipped into the production.

**Comment by sahil-shubham** [comment]
Going ahead and merging the PR then, you can always add your review to PRs if you have tested them yourself. Thanks for reporting the issue.

**Comment by proffapt** [comment]
aa.. I thought Rajiv already conveyed and we were waiting for your approval; will take care from next time.
